name: Example 1.
on:
  push:
    branches:
      - master
    paths:
      - 'examples/1-hello-world-lambda/*'
      - './.github/workflows/1-example-hello-world-lambda'
  pull_request_review:
    types:
      - submitted

env:
  EXAMPLE_LAMBDA: example-hello-world

jobs:
  build:
    name: Build Lambda Function
    runs-on: ubuntu-latest
    steps:
    - name: Check out code
      uses: actions/checkout@v3

    - name: Configure AWS credentials
      id: creds
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ github.event.inputs.region}}
    
    - name: Create Lambda Funtion with CDK
      run: |
        ls
        cd infra
        npm install
        npm ci
        npm install -g aws-cdk
        cdk synth
        cdk bootstrap
        cdk deploy $EXAMPLE_LAMBDA --require-approval never